Repository tarantool/cartridge, pull requests merged in 2022-06, with the labels that each got.

#1830 Make Raft failover unsupported error more readable
  cartridge/failover/raft.lua
  test/integration/raft_test.lua
Labels: 1sp, teamU

#1832 Add flaky mark to test_blinking_slow
  test/integration/state_machine_test.lua
Labels: 1sp, teamU

#1849 Update ddl to 1.6.1
  CHANGELOG.rst
  cartridge-scm-1.rockspec
Labels: teamU

#1845 Fix instance name config validation
  CHANGELOG.rst
  cartridge/argparse.lua
  test/unit/argparse_test.lua
Labels: 2sp, teamU
