Repository tarantool/cartridge, pull requests merged in 2022-01, with the labels that each got.

#1673 Update vshard to 0.1.19
  CHANGELOG.rst
  cartridge-scm-1.rockspec
Labels: feature, teamS

#1693 Allow to set up timeouts
  CHANGELOG.rst
  cartridge/twophase.lua
  test/integration/twophase_test.lua
Labels: cartridge, teamS

#1702 change self to group
  test/unit/argparse_test.lua
Labels: cartridge, teamX

#1716 Fix integration.failover_eventual.test_all_rw_failover
  test/integration/failover_eventual_test.lua
Labels: don't merge

#1711 Allow argparse option replication_synchro_quorum to be set as string
  CHANGELOG.rst
  cartridge/argparse.lua
  test/unit/argparse_test.lua
Labels: cartridge, teamX
