Repository tarantool/cartridge, pull requests merged in 2022-08, with the labels that each got.

#1863 SSL PoC
  .github/workflows/backend-test.yml
  CHANGELOG.rst
  cartridge.lua
  cartridge/argparse.lua
  cartridge/confapplier.lua
  cartridge/pool.lua
  cartridge/remote-control.lua
  cartridge/semver.lua
  cartridge/sslsocket.lua
  cartridge/test-helpers/server.lua
  cartridge/topology.lua
  cartridge/utils.lua
  cartridge/vshard-utils.lua
  test/integration/ssl_cert/ca.crt
  test/integration/ssl_cert/ca.key
  test/integration/ssl_cert/ca.srl
  test/integration/ssl_cert/client.crt
  test/integration/ssl_cert/client.enc.key
  test/integration/ssl_cert/client.key
  test/integration/ssl_cert/gen-gost.sh
  test/integration/ssl_cert/gen.sh
  test/integration/ssl_cert/gost.crt
  test/integration/ssl_cert/gost.key
  test/integration/ssl_cert/openssl.cnf
  test/integration/ssl_cert/server.crt
  test/integration/ssl_cert/server.enc.key
  test/integration/ssl_cert/server.key
  test/integration/ssl_test.lua
  test/unit/remote_control_ssl_test.lua
  test/unit/ssl_cert/ca.crt
  test/unit/ssl_cert/ca.key
  test/unit/ssl_cert/ca.srl
  test/unit/ssl_cert/client.crt
  test/unit/ssl_cert/client.enc.key
  test/unit/ssl_cert/client.key
  test/unit/ssl_cert/gen-gost.sh
  test/unit/ssl_cert/gen.sh
  test/unit/ssl_cert/gost.crt
  test/unit/ssl_cert/gost.key
  test/unit/ssl_cert/openssl.cnf
  test/unit/ssl_cert/server.crt
  test/unit/ssl_cert/server.enc.key
  test/unit/ssl_cert/server.key
Labels: 21sp, blocked

#1883 Add GraphQL examples to docs
  cartridge/issues.lua
  rst/topics/failover.rst
Labels: 1sp, teamU

#1889 Update vshard to 0.1.21
  CHANGELOG.rst
  cartridge-scm-1.rockspec
Labels: 1sp, blocked, teamU

#1891 Replace semver.lua with vshard.version
  cartridge/semver.lua
  cartridge/utils.lua
Labels: 1sp, teamU

#1888 Remote control suspend resume
  CHANGELOG.rst
  cartridge/confapplier.lua
  cartridge/remote-control.lua
  test/unit/remote_control_test.lua
Labels: teamU
